"""复现执行器——克隆官方代码进 Docker 沙箱，LLM 驱动「装环境→跑通」循环。

流程：
  1. git clone 到 ``<repro_dir>/repo/``；
  2. LLM 读 README + 文件清单，生成安装与运行命令（JSON plan）；
  3. 把 plan 写成 ``rc_reproduce_plan.json`` + 驱动脚本 ``rc_reproduce_entry.py``，
     用 :class:`DockerSandbox.run_project` 在容器里顺序执行；
  4. 失败则把 stdout/stderr 尾部喂回 LLM 出修复方案（文件编辑 + 新命令），
     循环上限 ``config.reproduce.max_rounds``，总预算 ``time_budget_sec``；
  5. 汇总实测指标（SandboxResult.metrics + staging 目录里的 results*.json）。

范式参考 pipeline/stage_impls/_execution.py 的 ITERATIVE_REFINE 循环与
pipeline/experiment_repair.py 的诊断修复逻辑；LLM 不可用时退化为
启发式单发（requirements.txt + 猜入口脚本）。
"""

from __future__ import annotations

import dataclasses
import json
import logging
import os
import re
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from researchclaw.config import RCConfig

logger = logging.getLogger(__name__)

_README_CANDIDATES = ("README.md", "README.rst", "README.txt", "README", "readme.md")
_ENTRY_CANDIDATES = ("main.py", "train.py", "run.py", "eval.py", "evaluate.py", "test.py")
_PLAN_FILE = "rc_reproduce_plan.json"
_ENTRY_FILE = "rc_reproduce_entry.py"
_MAX_STDERR_TAIL = 3000
_MAX_STDOUT_TAIL = 2000
_MAX_README_CHARS = 6000
_MAX_LISTING_ITEMS = 80

# 驱动脚本（静态内容）：在容器里顺序执行 plan 中的 shell 命令。
# entrypoint.sh 的 phase 0/1（pip install requirements.txt / setup.py）在此
# 之前已跑过；这里执行 LLM 给出的安装+运行命令。stdout 直通容器日志。
_DRIVER_SCRIPT = '''\
"""Auto-generated by researchclaw.reproduce — runs rc_reproduce_plan.json."""
import json
import subprocess
import sys
import time
from pathlib import Path

plan = json.loads(Path("{plan_file}").read_text(encoding="utf-8"))
commands = plan.get("commands") or []
budget = float(plan.get("budget_sec", 3600))
stop_on_error = bool(plan.get("stop_on_error", True))
start = time.monotonic()
exit_code = 0
for i, cmd in enumerate(commands, 1):
    remaining = budget - (time.monotonic() - start)
    if remaining <= 0:
        print(f"[rc-driver] time budget exhausted before cmd {{i}}", flush=True)
        exit_code = 124
        break
    print(f"\\n=== [rc-driver] cmd {{i}}/{{len(commands)}}: {{cmd}} ===", flush=True)
    try:
        cp = subprocess.run(cmd, shell=True, timeout=remaining, check=False)
        rc = cp.returncode
    except subprocess.TimeoutExpired:
        print(f"[rc-driver] cmd {{i}} timed out", flush=True)
        rc = 124
    if rc != 0:
        print(f"[rc-driver] cmd {{i}} failed with exit {{rc}}", flush=True)
        exit_code = rc if isinstance(rc, int) else 1
        if stop_on_error:
            break
sys.exit(exit_code)
'''


@dataclass
class ReproductionResult:
    """一次复现执行的结果。"""

    ok: bool
    repo_url: str
    repo_dir: str
    rounds_used: int
    elapsed_sec: float
    measured_metrics: dict[str, float] = field(default_factory=dict)
    run_history: list[dict[str, Any]] = field(default_factory=list)
    final_error: str = ""
    clone_ok: bool = True


def _extract_json(text: str) -> dict[str, Any]:
    """从 LLM 回复里抠出第一个 JSON 对象；失败返回 {}。"""
    m = re.search(r"\{.*\}", text, re.DOTALL)
    if not m:
        return {}
    try:
        data = json.loads(m.group(0))
    except json.JSONDecodeError:
        return {}
    return data if isinstance(data, dict) else {}


def _tail(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    return f"[...truncated {len(text) - limit} chars...]\n" + text[-limit:]


def _git_clone(repo_url: str, dest: Path, timeout_sec: int) -> tuple[bool, str]:
    """浅克隆 repo；返回 (ok, error)。任何失败都不抛异常。"""
    env = dict(os.environ, GIT_TERMINAL_PROMPT="0")
    try:
        cp = subprocess.run(
            ["git", "clone", "--depth", "1", repo_url, str(dest)],
            capture_output=True,
            text=True,
            timeout=timeout_sec,
            check=False,
            env=env,
        )
    except FileNotFoundError:
        return False, "git 不可用"
    except subprocess.TimeoutExpired:
        return False, f"git clone 超时（>{timeout_sec}s）"
    if cp.returncode != 0:
        return False, _tail((cp.stderr or cp.stdout or "git clone failed").strip(), 500)
    return True, ""


def _read_readme(repo_dir: Path) -> str:
    for name in _README_CANDIDATES:
        p = repo_dir / name
        if p.is_file():
            try:
                return p.read_text(encoding="utf-8", errors="replace")[:_MAX_README_CHARS]
            except OSError:
                continue
    return ""


def _repo_listing(repo_dir: Path) -> str:
    items: list[str] = []
    for p in sorted(repo_dir.iterdir()):
        if p.name.startswith(".") or p.name.startswith("rc_reproduce"):
            continue
        items.append(("d " if p.is_dir() else "f ") + p.name)
        if len(items) >= _MAX_LISTING_ITEMS:
            break
    return "\n".join(items)


def _apply_file_edits(repo_dir: Path, edits: list[dict[str, Any]]) -> list[str]:
    """应用 LLM 给的文件编辑；返回已应用的文件列表。

    路径安全：拒绝绝对路径与 ``..``，只允许写 repo 内的文本文件。
    """
    applied: list[str] = []
    for edit in edits[:10]:
        if not isinstance(edit, dict):
            continue
        rel = str(edit.get("path") or "").strip()
        if not rel:
            continue
        target = (repo_dir / rel).resolve()
        if not str(target).startswith(str(repo_dir.resolve()) + os.sep):
            logger.warning("Rejecting edit outside repo: %s", rel)
            continue
        try:
            if edit.get("find") is not None and edit.get("replace") is not None:
                old_text = target.read_text(encoding="utf-8")
                find = str(edit["find"])
                if find not in old_text:
                    logger.warning("Edit find-string not present in %s", rel)
                    continue
                target.write_text(
                    old_text.replace(find, str(edit["replace"]), 1), encoding="utf-8"
                )
            elif edit.get("content") is not None:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(str(edit["content"]), encoding="utf-8")
            else:
                continue
            applied.append(rel)
        except (OSError, UnicodeDecodeError) as exc:
            logger.warning("Failed to apply edit to %s: %s", rel, exc)
    return applied


class ReproductionRunner:
    """在 Docker 沙箱里复现一篇论文的官方代码。"""

    def __init__(self, config: RCConfig, llm: Any = None) -> None:
        self.config = config
        self.llm = llm
        self.rc = config.reproduce

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def run(
        self,
        repo_url: str,
        repro_dir: Path,
        *,
        paper_title: str = "",
        paper_text: str = "",
    ) -> ReproductionResult:
        """克隆 + 沙箱「装环境→跑通」循环；结果落盘 reproduction_log.json。"""
        repro_dir.mkdir(parents=True, exist_ok=True)
        start = time.monotonic()

        # --- 1. clone ---
        repo_dir = repro_dir / "repo"
        if repo_dir.exists():
            logger.info("Reusing existing clone at %s", repo_dir)
            clone_ok, clone_err = True, ""
        else:
            clone_ok, clone_err = _git_clone(repo_url, repo_dir, self.rc.clone_timeout_sec)
        if not clone_ok:
            result = ReproductionResult(
                ok=False,
                repo_url=repo_url,
                repo_dir=str(repo_dir),
                rounds_used=0,
                elapsed_sec=time.monotonic() - start,
                final_error=f"克隆失败：{clone_err}",
                clone_ok=False,
            )
            self._write_log(repro_dir, result, paper_title)
            return result

        # --- 2. sandbox ---
        if not self._docker_ready():
            result = ReproductionResult(
                ok=False,
                repo_url=repo_url,
                repo_dir=str(repo_dir),
                rounds_used=0,
                elapsed_sec=time.monotonic() - start,
                final_error="Docker 不可用（复现需要实验沙箱容器）",
            )
            self._write_log(repro_dir, result, paper_title)
            return result

        sandbox = self._make_sandbox(repro_dir / "sandbox_work")
        readme = _read_readme(repo_dir)
        listing = _repo_listing(repo_dir)

        # --- 3. plan→run→fix 循环 ---
        history: list[dict[str, Any]] = []
        plan = self._make_plan(repo_dir, readme, listing, paper_title, paper_text)
        measured: dict[str, float] = {}
        final_error = ""
        ok = False
        rounds = 0

        for round_no in range(1, self.rc.max_rounds + 1):
            elapsed = time.monotonic() - start
            remaining = self.rc.time_budget_sec - elapsed
            if remaining <= 30:
                final_error = f"复现时间预算耗尽（{self.rc.time_budget_sec}s）"
                break
            rounds = round_no
            commands = [str(c) for c in (plan.get("commands") or []) if str(c).strip()]
            if not commands:
                final_error = "LLM 未给出可执行命令"
                break
            logger.info(
                "Reproduction round %d/%d (%.0fs elapsed): %s",
                round_no, self.rc.max_rounds, elapsed, commands,
            )

            self._write_driver(repo_dir, commands, budget_sec=remaining)
            run_result = sandbox.run_project(
                repo_dir,
                entry_point=_ENTRY_FILE,
                timeout_sec=int(remaining),
                env_overrides={"PYTHONUNBUFFERED": "1"},
            )
            round_metrics = self._collect_metrics(sandbox.workdir, run_result.metrics)
            record = {
                "round": round_no,
                "commands": commands,
                "returncode": run_result.returncode,
                "timed_out": run_result.timed_out,
                "elapsed_sec": round(run_result.elapsed_sec, 1),
                "metrics": round_metrics,
                "stdout_tail": _tail(run_result.stdout or "", _MAX_STDOUT_TAIL),
                "stderr_tail": _tail(run_result.stderr or "", _MAX_STDERR_TAIL),
            }
            history.append(record)

            if run_result.returncode == 0:
                ok = True
                measured = round_metrics
                logger.info("Reproduction succeeded in round %d", round_no)
                break

            # 失败 → LLM 诊断修复；LLM 不可用或预算见底则只跑一发
            if self.llm is None or round_no >= self.rc.max_rounds:
                final_error = _tail(run_result.stderr or run_result.stdout or "", 500)
                break
            fix = self._make_fix(plan, record, readme, listing)
            diagnosis = str(fix.get("diagnosis") or "")
            record["diagnosis"] = diagnosis[:500]
            applied = _apply_file_edits(repo_dir, list(fix.get("file_edits") or []))
            record["applied_edits"] = applied
            new_commands = [
                str(c) for c in (fix.get("commands") or []) if str(c).strip()
            ]
            if not new_commands and not applied:
                final_error = "LLM 未能给出修复方案：" + _tail(
                    run_result.stderr or "", 300
                )
                break
            if new_commands:
                plan["commands"] = new_commands

        result = ReproductionResult(
            ok=ok,
            repo_url=repo_url,
            repo_dir=str(repo_dir),
            rounds_used=rounds,
            elapsed_sec=time.monotonic() - start,
            measured_metrics=measured,
            run_history=history,
            final_error="" if ok else (final_error or "复现未跑通"),
        )
        self._write_log(repro_dir, result, paper_title)
        return result

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _docker_ready(self) -> bool:
        from researchclaw.experiment.docker_sandbox import DockerSandbox

        if not DockerSandbox.check_docker_available():
            return False
        image = self.config.experiment.docker.image
        if not DockerSandbox.ensure_image(image):
            logger.error("Docker image %s not found locally", image)
            return False
        return True

    def _make_sandbox(self, workdir: Path):
        """复用 experiment.docker 段的镜像/资源，网络策略按 reproduce 段覆盖。"""
        from researchclaw.experiment.docker_sandbox import DockerSandbox

        docker_cfg = dataclasses.replace(
            self.config.experiment.docker,
            network_policy=self.rc.network_policy,
        )
        return DockerSandbox(docker_cfg, workdir)

    def _write_driver(self, repo_dir: Path, commands: list[str], *, budget_sec: float) -> None:
        (repo_dir / _PLAN_FILE).write_text(
            json.dumps(
                {"commands": commands, "budget_sec": int(budget_sec), "stop_on_error": True},
                ensure_ascii=False,
                indent=2,
            ),
            encoding="utf-8",
        )
        (repo_dir / _ENTRY_FILE).write_text(
            _DRIVER_SCRIPT.format(plan_file=_PLAN_FILE), encoding="utf-8"
        )

    def _make_plan(
        self,
        repo_dir: Path,
        readme: str,
        listing: str,
        paper_title: str,
        paper_text: str,
    ) -> dict[str, Any]:
        """首轮执行计划：LLM 读 README 生成；无 LLM 走启发式。"""
        if self.llm is None:
            return self._heuristic_plan(repo_dir)
        system = (
            "你是资深 ML 工程师，要在 Docker 容器（已预装 PyTorch 科学计算栈）里"
            "跑通一篇论文的官方代码。输出严格 JSON。"
        )
        prompt = (
            f"论文：{paper_title or '(未知)'}\n"
            f"{('论文摘要：' + paper_text[:1500]) if paper_text else ''}\n\n"
            f"仓库文件清单：\n{listing}\n\n"
            f"README（截断）：\n{readme or '(无 README)'}\n\n"
            "给出在这个容器里把代码跑通的命令序列。要求：\n"
            "1. 优先小规模 smoke 配置（少量 epoch/步数/样本），目标是先跑通再谈精度；\n"
            "2. 数据集下载命令放在前面（容器运行阶段有网络）；\n"
            "3. 若有 requirements.txt 先 pip install -r requirements.txt；\n"
            "4. 每条命令是一个 shell 字符串，按执行顺序排列；\n"
            "5. 训练脚本加非交互参数，禁止需要 stdin 的命令。\n"
            '输出 JSON：{"commands": ["..."], "notes": "一句话说明"}'
        )
        try:
            resp = self.llm.chat(
                [{"role": "user", "content": prompt}],
                system=system,
                json_mode=True,
                max_tokens=1500,
            )
            plan = _extract_json(resp.content)
            if plan.get("commands"):
                return plan
        except Exception as exc:  # noqa: BLE001
            logger.warning("LLM plan failed, falling back to heuristic: %s", exc)
        return self._heuristic_plan(repo_dir)

    def _heuristic_plan(self, repo_dir: Path) -> dict[str, Any]:
        """无 LLM 时的单发启发式：requirements.txt + 猜入口脚本。"""
        commands: list[str] = []
        if (repo_dir / "requirements.txt").is_file():
            commands.append("pip install -r requirements.txt")
        for name in _ENTRY_CANDIDATES:
            if (repo_dir / name).is_file():
                commands.append(f"python3 {name}")
                break
        return {"commands": commands, "notes": "heuristic fallback (no LLM)"}

    def _make_fix(
        self,
        plan: dict[str, Any],
        record: dict[str, Any],
        readme: str,
        listing: str,
    ) -> dict[str, Any]:
        """把失败日志喂回 LLM，生成修复方案（文件编辑 + 新命令）。"""
        system = (
            "你是资深 ML 工程师，在修复一个跑不通的论文复现环境。"
            "输出严格 JSON，不要多余文字。"
        )
        prompt = (
            f"仓库文件清单：\n{listing}\n\n"
            f"README（截断）：\n{readme[:3000]}\n\n"
            f"上一轮命令：{json.dumps(record.get('commands'), ensure_ascii=False)}\n"
            f"退出码：{record.get('returncode')}"
            f"{'（超时）' if record.get('timed_out') else ''}\n\n"
            f"stderr 尾部：\n{record.get('stderr_tail') or '(空)'}\n\n"
            f"stdout 尾部：\n{record.get('stdout_tail') or '(空)'}\n\n"
            "诊断失败原因并给出最小修复。输出 JSON：\n"
            '{"diagnosis": "一句话根因", '
            '"file_edits": [{"path": "相对路径", "content": "完整新内容"} '
            '或 {"path": "...", "find": "原文", "replace": "替换为"}], '
            '"commands": ["新的命令序列"]}\n'
            "要求：编辑最少化；file_edits 最多 3 个文件；"
            "若是超时，把命令改成更小的 smoke 配置；若是缺依赖，加 pip install。"
        )
        try:
            resp = self.llm.chat(
                [{"role": "user", "content": prompt}],
                system=system,
                json_mode=True,
                max_tokens=3000,
            )
            return _extract_json(resp.content)
        except Exception as exc:  # noqa: BLE001
            logger.warning("LLM fix failed: %s", exc)
            return {}

    def _collect_metrics(
        self, sandbox_workdir: Path, sandbox_metrics: dict[str, object]
    ) -> dict[str, float]:
        """汇总本轮实测指标：SandboxResult.metrics + staging 里的 results*.json。"""
        from researchclaw.experiment.metrics import UniversalMetricParser

        collected: dict[str, float] = {}
        # staging 目录里的结果文件（repo 可能写到子目录，如 outputs/results.json）
        staging_dirs = sorted(
            sandbox_workdir.glob("_docker_project_*"),
            key=lambda p: p.stat().st_mtime if p.exists() else 0,
        )
        if staging_dirs:
            staging = staging_dirs[-1]
            for jf in list(staging.rglob("*.json"))[:20]:
                if not re.search(r"result|metric|score|eval", jf.name, re.IGNORECASE):
                    continue
                try:
                    if jf.stat().st_size > 2 * 1024 * 1024:
                        continue
                    data = json.loads(jf.read_text(encoding="utf-8", errors="replace"))
                except (OSError, json.JSONDecodeError):
                    continue
                if not isinstance(data, dict):
                    continue
                for key, val in data.items():
                    if isinstance(val, (int, float)):
                        collected.setdefault(str(key), float(val))
                    elif isinstance(val, dict):
                        for sub_key, sub_val in val.items():
                            if isinstance(sub_val, (int, float)):
                                collected.setdefault(f"{key}/{sub_key}", float(sub_val))
        # SandboxResult.metrics（stdout 正则 + staging 根 results.json）优先
        for key, val in (sandbox_metrics or {}).items():
            if isinstance(val, (int, float)):
                collected[str(key)] = float(val)
        # UniversalMetricParser 再过一遍 staging 根目录（CSV 等格式）
        if staging_dirs:
            try:
                parsed = UniversalMetricParser().parse(staging_dirs[-1])
                for key, val in parsed.to_flat_metrics().items():
                    collected.setdefault(key, val)
            except Exception:  # noqa: BLE001
                pass
        return collected

    def _write_log(self, repro_dir: Path, result: ReproductionResult, paper_title: str) -> None:
        payload = {
            "paper_title": paper_title,
            "repo_url": result.repo_url,
            "ok": result.ok,
            "clone_ok": result.clone_ok,
            "rounds_used": result.rounds_used,
            "elapsed_sec": round(result.elapsed_sec, 1),
            "measured_metrics": result.measured_metrics,
            "final_error": result.final_error,
            "run_history": result.run_history,
        }
        try:
            (repro_dir / "reproduction_log.json").write_text(
                json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8"
            )
        except OSError:
            logger.warning("Failed to write reproduction_log.json in %s", repro_dir)
